### ISSUE TITLE
1.21 update

### ISSUE THREAD

**Issue by jinkhya** [jeremiahwinsley/novillagerdm#3]
Hello,
Could this mod be update to 1.21.1 please?
I have some players spam killing villagers on ATM10, it would be nice to not have the console filled with the villager death messages :')
Ofc if you're busy IRL I totally understand, life comes first!
Thanks in advance,
Jin

**Comment by jeremiahwinsley** [comment]
Sure, I'll work on this soon.

**Comment by jeremiahwinsley** [comment]
https://github.com/jeremiahwinsley/novillagerdm/releases/tag/v6.0.0 has been published, should be available on CF and Modrinth soon.

**Comment by jinkhya** [comment]
Wow thank you so much for doing this so quickly!
